### ISSUE TITLE
OOM error while deploying it on SageMaker

### ISSUE THREAD

**Issue by ravilkashyap** [awslabs/extending-the-context-length-of-open-source-llms#5]
I'm following this notebook to deploy FalconLite on Sagemaker - https://github.com/awslabs/extending-the-context-length-of-open-source-llms/blob/main/custom-tgi-ecr/deploy.ipynb

Since FalconLite is supposed to run on a single GPU, I've tried running it on `ml.g5.2xlarge` / `ml.g5.4xlarge`/ `ml.g5.8xlarge` with `num_gpu = 1`. Even though there's sufficient GPU memory, I still get OOM error.

<img width="1375" alt="Screenshot 2023-08-07 at 5 04 59 PM" src="https://github.com/awslabs/extending-the-context-length-of-open-source-llms/assets/20355455/f1e4fc51-5b3c-40a9-a5be-1229ea270351">

**Comment by ravilkashyap** [comment]
@yihyap can you help with this? Any pointers?

**Comment by chenwuperth** [comment]
FalconLite requires at least 30GB GPU RAM to run. The single GPU on ml.g5.2xlarge / ml.g5.4xlarge/ ml.g5.8xlarge all have a capacity of 24GB < 30GB. To successfully run FalconLite on a single GPU, that GPU needs to have a RAM greater than 30GB, such as A100 (with 40GB or 80GB RAM).

**Comment by ravilkashyap** [comment]
Thanks for your reply @chenwuperth 
Based on your suggestion, I found ml.g4dn.12xlarge to have sufficient memory - 
4 GPU with 16GB each resulting in 64GB GPU memory and 192GB instance memory

I was hoping that sharding will take care of loading the model across multiple GPUs and it is able to do so - 
<img width="1370" alt="Screenshot 2023-08-14 at 3 54 07 PM" src="https://github.com/awslabs/extending-the-context-length-of-open-source-llms/assets/20355455/47c7bfd8-a05d-4989-970f-e00a70da7948">

But once the webserver starts, I get this error - 
<img width="1387" alt="Screenshot 2023-08-14 at 3 54 34 PM" src="https://github.com/awslabs/extending-the-context-length-of-open-source-llms/assets/20355455/51d4948c-1b28-4e01-ba81-4ce81af3238d">

I tried reducing the token count but I still get the same error.

**Comment by chenwuperth** [comment]
would you be able to expand the arrow and screenshot the detailed error message in this line? thanks
```bash
RuntimeError: CUDA error: CUBLAS_STATUS_NOT...
```

**Comment by ravilkashyap** [comment]
Oh sorry, I missed to expand that. Please take a look here - 
<img width="1388" alt="Screenshot 2023-08-14 at 10 24 25 PM" src="https://github.com/huggingface/text-generation-inference/assets/20355455/963860dc-bd6a-473e-b009-6c7386a329ae">

**Comment by yinsong1986** [comment]
I think it is GPU memory issues,  using`ml.g5.12xlarge` should be able to solve the issues. Cheers!

**Comment by chenwuperth** [comment]
As suggested in the FalconLite document, `g5.12x` instance (or above) would be the hardware to run FalconLite.
