### ISSUE TITLE
Templates need to be in .github

### ISSUE THREAD

**Issue by hyandell** [awslabs/extending-the-context-length-of-open-source-llms#8]
I believe the ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE files need to be in a .github directory to work.

**Comment by hyandell** [comment]
Additionally you'd need something in those files. They're currently empty.

**Comment by chenwuperth** [comment]
ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE files are added with content.
